[package]
name = "merge-jwl"
version = "0.1.0"
authors = ["abdon-copper <59224618+abdon-copper@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
